env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-essential
  - plugin:nuxt/recommended
  - plugin:prettier/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - prettier
rules: {
  "vue/multi-word-component-names": 0,
  "prettier/prettier": 1,
}
